### ISSUE TITLE
Potentially add filtering functionality to survey_visit endpoint

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#105]
### Overview
We need a suvery_visit (previously HOMESURVEY) endpoint.

Attributes
- Id
- homeId
- surveyorId 
- surveyId
- surveyCompleted
- True, false

<img width="552" alt="image" src="https://user-images.githubusercontent.com/565647/200717202-d6e73bce-3f3b-4ff4-a748-36b672667819.png">

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/565647/200719257-78b10b91-66a7-4a9e-91f8-26172bb2cf52.png">

see https://www.forcedive.com/surveyor/dashboard

Left To do:
- [ ] Limit to 30 items
- [ ] Add filtering.

**Comment by mzagaja** [comment]
This actually exists in the app as `suvery_visits` right now, but the endpoint needs to be updated and created.

**Comment by smcclure17** [comment]
ah cool--thanks for the context. 

So are we just looking to update/edit the existing [`survey_visits`](https://github.com/codeforboston/urban-league-heat-pump-accelerator/blob/main/backend/app/controllers/survey_visits_controller.rb) endpoint? Or do we need to add a new, `survey_visit` endpoint, too?

**Comment by mzagaja** [comment]
@smcclure17 Apologies for the tardy reply. The `survey_visit` endpoint is set, so just needs adjusting so that its responses conform to the specification in the original Issue. For example it will need the filtering functionality enumerated, as well as pagination.
