### ISSUE TITLE
Frontend-fix admin tab selection

### ISSUE THREAD

**Issue by Zevez7** [codeforboston/urban-league-heat-pump-accelerator#124]
If you watch this video, you can see the bug. When you click on the user tab and click on the user in the table. It takes you to the user profile page. Then when you return to the admin tab page. The home page is selected and is displayed in the tab. What should really happen is the user tab should be selected and displayed. Because you are currently viewing user and go back to the admin tab page should still display the user tab so you can select another user. 

You need to use redux tool kit to create a tabDisplay slice so that it keeps a record of the last tab you have selected. The default tab display should be the home tab but when you click on the user tab, the tabDisplay slice should be switch to "user" so that it will display the user tab whenever you navigate to admin page. Next, if you click the home tab, the slice should switch to "home" and only display home table when you navigate to the admin page.

https://watch.screencastify.com/v/5zVtBdALSTaWfQP4q31P

**Comment by Tcoding12** [comment]
which branch should i push/fork  the code to/from

**Comment by Zevez7** [comment]
Frontend-main

**Comment by Zevez7** [comment]
not needed anymore
