### ISSUE TITLE
Implement survey page

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#129]
Looks like the wireframe is a separate issue, just wanted to make this issue for tracking purposes. Specifics can be found in the Frontend Dev Map document.

Notes:
1. Make sure everything lines up with the wireframe
2. further wording for the form is TBD, make sure to check back in on that before the next meeting
3. verify page responsiveness

**Comment by mattdelsordo** [comment]
I wanted to assign this to myself but it doesn't look like I have that permission in this project so... let it be known I'm working on this :)

**Comment by Zevez7** [comment]
Hey are you still working on this?

**Comment by Zevez7** [comment]
If you're unable to get this completed Monday. I will take over since this is a priority now.

**Comment by Zevez7** [comment]
https://docs.google.com/document/d/1-scDkNzJ3MnItwwOqHx58yyNF10xKyO-rhRxYq4mQo0/edit

If you scroll down to the highlighted yellow online survey section. That's an outline of what the survey should look like.

**Comment by mattdelsordo** [comment]
Yup! Sorry that I wasn't able to make it this last week. I've created a survey page already but I've got to wire it up with react-hook-forms still. I'll get this done by Monday.

**Comment by mattdelsordo** [comment]
Resolved by #150
