### ISSUE TITLE
Create website homepage

### ISSUE THREAD

**Issue by kbierce** [codeforboston/urban-league-heat-pump-accelerator#151]
Drafted by Katharine. Pending stakeholder review as of Feb 5, 2023.

Chris to do:
- Comment on [copy edits for website homepage](https://docs.google.com/document/d/16awSAJEyP5s6Jy2uL6gO4LKRdkthi5Lk-oOzIZG3K6w/edit)
- Chris to check % for heat pump savings (up to 50%? 15%?)

**Comment by kbierce** [comment]
Summary of edits/questions I see remaining:

For Chris

- Homepage: Share [testimonial photos + text](https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g20e321d513a_0_29) ** blocker for homepage
- [“Spread the Word” page](https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g202698b06e5_0_0): share info from Heat Smart Alliance

DISCUSS on 2/21 - General review: look at top navigation and comment 
DISCUSS what google drive the ‘social sharing’ copy should live on – current drive is not publicly viewable; should this be in Katharine’s GDrive?? Urban League? 

For frontend team
[Update images to edited versions](https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g20e321d513a_0_0) on homepage
Create the [“Spread the Word” page](https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g202698b06e5_0_0) 

Katharine to do
For the [“Spread the Word” page](https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g202698b06e5_0_0):
 	Create flyer for local business
 	Create social sharing copy (TBD on where this should live; should it be a webpage or Gdoc)

**Comment by kbierce** [comment]
Need Chris to comment on the footer at 2/28 meetup.

![Image](https://user-images.githubusercontent.com/4795609/221247438-ef20de11-d436-4125-876d-e2bc1872d549.jpg)

**Comment by S7mitbarua** [comment]
Using Nn/g ([[Nielsen Norman Guideline](https://www.nngroup.com/articles/footers/)s])), I have designed the footer. I have added the content headers: Learn, Legal, and Get in Touch. Based on the previously designed footer, I have used the existing address.
