### ISSUE TITLE
FAQ page - Public View

### ISSUE THREAD

**Issue by thiagobardini** [codeforboston/urban-league-heat-pump-accelerator#169]
@S7mitbarua 
- Improved wireframe for FAQ Page.
[Link to Figma](https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=305%3A6119&t=kEQNBtYEP5jO7l81-4)
https://bhpa.vercel.app/public/faq

**Comment by S7mitbarua** [comment]
Opened ticket! For FAQ- I need to ask Katharine or Chris what kinds of should BHPA should have on the Frequently Asked Questions sections (before we further) attempt to design.

**Comment by Rando-cal** [comment]
I coded the basic FAQ as seen on https://bhpa.vercel.app/public/faq . We need the content from Chris I believe
