### ISSUE TITLE
Back-end support for reCAPTCHA

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#208]
The front-end part of this is already done (except we still need the API token). Reference: https://developers.google.com/recaptcha/docs/v3

1. We need to sign up for an API key pair (we're using reCAPTCHA v3): https://www.google.com/recaptcha/admin/create
2. The front-end will get a token that will get sent to the back-end along with the survey data in a header/the body/a parameter (whatever is easiest for the back-end team)
3. The back-end needs to validate the token with Google (https://developers.google.com/recaptcha/docs/verify). This involves making a normal POST request to Google's endpoint with the token
4. The back-end will get back a value from 0 to 1: 1 = user is very likely human, 0 user is likely a bot. They recommend a threshold of 0.5 for rejecting data, but we can also just store the score along with the data and decide what to do with it later. 
5. If we're rejecting data then the survey submission endpoint should probably return some sort of 4xx error so the front-end can display an error.

**Comment by mikelynch** [comment]
Likely requires migration to add “spam-likelihood” attribute to `survey_visits`.

**Comment by mikelynch** [comment]
Required steps:
1. Permit reCAPTCHA token on survey_visits controller (at least for create method).
2. Add new column to `survey_visits` to store “spam-likelihood” attribute.
3. Add logic to (without blocking) look up reCAPTCHA user response token. This needs to be done within 2 minutes, but shouldn't block the puma worker. Look at sidekick?

**Comment by mikelynch** [comment]
One disadvantage of Sidekiq (and several other ActiveJob backends) is that it requires Redis as well. Could instead look at:
* [Sucker Punch](https://github.com/brandonhilkert/sucker_punch) – no additional dependency
* [queue_classic](https://github.com/QueueClassic/queue_classic) – uses existing Postgres dependency
