### ISSUE TITLE
Setup New Relic and Observability

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#21]
### Overview
In order to keep an eye on the performance of our app we want the[ New Relic Ruby Gem](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby/) installed.

### Action Items
- Get setup with a Code for Boston New Relic account (contact @mzagaja).
- Get a New Relic API Key
- Add the New Relic gem to the backend.

**Comment by aTegart** [comment]
Added the gem a little while ago
dcdb6cb83a9dbddf1c09dd346d73e9fef25b93b0
