### ISSUE TITLE
About BHPA page created  > Public View - Follow the wireframe on Figma

### ISSUE THREAD

**Issue by thiagobardini** [codeforboston/urban-league-heat-pump-accelerator#216]
**Description**
- Created a page for the About BHPA section as per the wireframe on Figma.
- Only create a file in this path: PUBLIC > PAGES > AboutHeatPump.js 
- Create a route on the PublicContainer.js (Do not create links on the navbar using react-router-dom).
    `<Route path="/about-heat-pump" element={<AboutHeatPump />}></Route>`       
- Partners logo images are available in this path: FRONT > SRC > IMAGES.
- For the "City of Boston - PowerCorpsBOS (PCB)" logo, resizing and opacity adjustments can be done later

- Figma link: https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=898-12458&t=hpcnMVa7pdeWtzGO-4

**Note:**
- For design concerns, please contact Sumit B. (@S7mitbarua). For content-related questions, please reach out to Katharine Bierce (@kbierce). For code-related concerns, please contact Thiago Bardini (@thiagobardini)  or Dat Nguyen (@Zevez7).

**Comment by S7mitbarua** [comment]
Design in progress. ETA completion by Monday 3/13 by 9 PM 
https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=0%3A1&t=rqpwxZ9uK6znH9G0-0 (Redesign About BHPA page)

**Comment by S7mitbarua** [comment]
Design Completed.

**Comment by S7mitbarua** [comment]
Alignment, Space issues, and logo have been fixed. The design is now completed. @thiagobardini

**Comment by thiagobardini** [comment]
Ready to code - Wireframe created for the 'About BHPA' page.

**Comment by S7mitbarua** [comment]
Design updated @thiagobardini 

Please review the updated design: https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1915-12752&t=HH786kTIiN2hyYmy-0
