### ISSUE TITLE
Setup Ubuntu Server on AWS for Deployment

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#22]
### Overview
After getting credentials/AWS from @mzagaja, setup an EC2 instance to host our Rails app. 

### Action Items
- Make sure your SSH public key is updated in your GitHub profile or send it to Matt
- Login to the server using SSH
- Following the template below, install the necessary applications and make configuration changes for deployment.
- Create a deployment user for the rails app called `heat-pump` or similar. https://github.com/mzagaja/infrastructure/blob/master/bin/add_app_to_server.sh#L8
- Create user accounts with public keys from GitHub for any teammates that might want access.
- Add all teammates public keys to the `heat-pump` user so they can deploy to production.

### Resources/Instructions
- [Matt's Server Setup Template](https://github.com/mzagaja/infrastructure/blob/master/bin/server_setup.sh)

**Comment by challyed** [comment]
**Make sure your SSH public key is updated in your GitHub profile or send it to Matt**
@mzagaja  Just updated my public key

**Comment by challyed** [comment]
did the following three task

- [x ] Make sure your SSH public key is updated in your GitHub profile or send it to Matt
- [x] Login to the server using SSH
- [x ] Following the template below, install the necessary applications and make configuration changes for deployment

is the line "User Setup Steps for MAPC Users" the same as "Create a deployment user for the rails app called heat-pump or similar."

**Comment by mzagaja** [comment]
@challyed Actually the "create a deployment user for heat-pump or similar" is documented in https://github.com/mzagaja/infrastructure/blob/master/bin/add_app_to_server.sh. I forgot I had that in a separate file. So you should go through the first file first, then for setting up the heat-pump user follow the template I linked here.

**Comment by challyed** [comment]
Ended up naming the app 'heatpumpapp'

**Comment by challyed** [comment]
What is needed for app_url?
I am also guessing that the ruby version should be 3.1. 2

**Comment by mzagaja** [comment]
Yep Ruby version will be 3.1.2.

$APP_URL is what our domain will eventually be. We don't know what this is yet. Have to talk to Christopher Scranton about where it might land. You can maybe skip those steps with $APP_URL for now or use `heatpumpapp` in its place if it makes sense.

**Comment by mzagaja** [comment]
@challyed How is this looking? Should we plan to try and setup deployments this Tuesday?

**Comment by mzagaja** [comment]
Closing this since it is stale and because @zganger is setting us up in ECS instead.
