### ISSUE TITLE
Log IP address when survey submitted

### ISSUE THREAD

**Issue by mikelynch** [codeforboston/urban-league-heat-pump-accelerator#223]
Now that we're planning to allow anonymous users (i.e. not-logged in) to fill in the survey online, we'd like some logging in case this is abused by bad actors. When the survey is filled in, we will log the IP address – that way, if we see a flurry of odd responses in quick succession, we have a bit more data to look at on that side. This definitely isn't bullet-proof, but hopefully can catch some obvious issues.

**Comment by mikelynch** [comment]
Should be able to use http://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-ip

**Comment by mzagaja** [comment]
Need to check Docker container for:

bundle install failing to install smarter_csv gem natively.
And not automatically installing ruby 3.1.3 in RVM.
