### ISSUE TITLE
Add attributes for answers to survey meta-questions to survey_visit

### ISSUE THREAD

**Issue by mikelynch** [codeforboston/urban-league-heat-pump-accelerator#226]
We have the idea of a `survey_visit`, which represents a surveyor visiting a home that was assigned to them – whether or not they successfully did any more. We only create a `survey_response` and answers if the real survey was administered. However, there are “meta-questions” about whether the survey was administered at all, including:
* Does the home exist? Y/N
* Was anyone in? Y/N
* Were they the owner? Y/N
* When should the surveyor come back?

What else? @mzagaja , any thoughts?

The changes will need making on the model, but also the front end will need to handle these “hard-coded” meta-questions.

**Comment by mzagaja** [comment]
Just need the migration to add these attributes to the visit.

**Comment by mikelynch** [comment]
We should confirm with Christopher, but our understanding is that we're aren't planning to double-back to homes that we didn't manage to administer the survey to, so we should probably skip this and just add those questions to the start of the survey.

**Comment by aTegart** [comment]
Confirmed that all info collected will be in the form of 'normal' survey questions
