### ISSUE TITLE
Under Construction" page for Boston Heat Pump Accelerator (BHPA)

### ISSUE THREAD

**Issue by thiagobardini** [codeforboston/urban-league-heat-pump-accelerator#229]
**Figma** 
https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=2012-12815&t=8i9yJdWlF5FCxgZY-4

**Google Slide**
https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g230a43dc76b_0_0

**Comment by S7mitbarua** [comment]
@thiagobardini Right now, I see this page is empty (Check back later). I can start working on it. Let me know.

**Comment by thiagobardini** [comment]
@S7mitbarua Sumit, if you can just create something simple, I would appreciate it.

**Comment by S7mitbarua** [comment]
@thiagobardini Checkout in figma, is currently under construction: https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1104-12662&t=egYrxBRn9ZMWqDzy-0

**Comment by jedddill** [comment]
@thiagobardini check out this wireframe in Figma. Is that what you had in mind for this "Under Construction" Page? Open to ideas for improvement https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1288%3A12737&t=lPVeJdpxgvp3M6iE-1
