### ISSUE TITLE
Create responsive "BHPA Privacy" page design

### ISSUE THREAD

**Issue by S7mitbarua** [codeforboston/urban-league-heat-pump-accelerator#241]
Create a new page for the "BHPA Privacy" page that is responsive on both desktop and mobile platforms. Please refer to the Figma links provided below for the design specifications:

**Figma**
[Mobile](https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1915-12690&t=6YFUtMaAglm38YKP-4) | [Desktop](https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1915-12702&t=iEgCRTCy8n3zwaw9-4)
 
**File Path**
To implement the design in the following path: PUBLIC > PAGES.

**Custom CSS**
Please use either SX, Styled, or Theme to customize the CSS. Refer to the following links for instructions:
[SX](https://mui.com/material-ui/customization/how-to-customize/) | [Styled ](https://mui.com/system/styled/#difference-with-the-sx-prop)

**Pull Request**
Once you have completed the implementation, create a Pull Request to merge your changes into the Frontend_main branch. Please request a review from @thiagobardini before merging, and do not merge into the main branch.

**Note**
If you have any design-related concerns or code-related concerns, please contact @thiagobardini.

**Comment by S7mitbarua** [comment]
@thiagobardini

**Comment by thiagobardini** [comment]
Have you approved the page? @S7mitbarua

**Comment by S7mitbarua** [comment]
Waiting for Chris's approval Next Tuesday.

**Comment by S7mitbarua** [comment]
@thiagobardini Need to fix (UX design technical issues)

**Comment by S7mitbarua** [comment]
Mobile (Privacy Policy): https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1915-12690&t=IL6Sgo9OwtxHGdBU-0

Desktop (Privacy Policy): https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1915-12702&t=IL6Sgo9OwtxHGdBU-0

**Ready to code!** 

@thiagobardini

**Comment by mattdelsordo** [comment]
Closing this as done
