### ISSUE TITLE
Setup Endpoints for Geospatial Data

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#26]
### Overview
In order to do geospatial data analysis we need the PostGIS extension setup for Postgres + the RGeo gem.

### Action Items
- Setup PostGIS locally.
- Setup RGeo in the backend repo.
- Create a geospatial data column that matches what is available in the City of Boston dataset shapefile.
- Append geospatial data to the imported CSV data using a script.

### Resources/Instructions
- [Introduction to PostGIS by Paul Ramsay](https://www.youtube.com/watch?v=g4DgAVCmiDE)
- [Introduction to PostGIS](https://postgis.net/workshops/postgis-intro/)
- [RGeo Gem](https://github.com/rgeo/rgeo)

**Comment by mzagaja** [comment]
Dat explained they just need the latitude and longitude as imported from the Data team. It should be provided in two parts. First we need to add the lat/long to the homes. Secondarily we need to add a "start point" to the `Assignment`.

**Comment by mikelynch** [comment]
The `assignment` has a centroid location rather than “start point”. To get the start point, just find the lowest `visit_order` home with the appropriate `assignment_id`.
