### ISSUE TITLE
Get API key for ReCAPTCHA

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#266]
1. Login here with a Google account that we want to be associated with the project: https://www.google.com/recaptcha/admin/create
2. Label: whatever seems appropriate
3. `Score based (v3)` API key
4. Domain: our front-end URL
5. `ReCaptcha.js` in our front-end code is already looking for an environment variable called `REACT_APP_RECAPTCHA_KEY`, so we want to add that as an environment variable at build time in Vercel

**Comment by mattdelsordo** [comment]
We got it! @thiagobardini assigning this to you so you can add the key to vercel. I'll DM you with specifics.

**Comment by thiagobardini** [comment]
I created the variable in Vercel. Let's merge your ticket and see if this is working. Let me know what you think.
