### ISSUE TITLE
Redesign "Add Your Voice" and "About Us" cards on homepage

### ISSUE THREAD

**Issue by jedddill** [codeforboston/urban-league-heat-pump-accelerator#269]
Cards under the Hero image need redesigning without changing the content too much

**Figma**
Desktop: https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=2004-12682&t=8i9yJdWlF5FCxgZY-4
Mobile: https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=2047-12702&t=8i9yJdWlF5FCxgZY-4

**Google Slide**
https://docs.google.com/presentation/d/1Yr7Y5J1rLDHJLfOcklB42wzCqE9JHFSeD9tuG0T3ReE/edit#slide=id.g230a43dc76b_0_6

**Comment by JulianaDonovan** [comment]
I re-designed them . Let me know your thoughts!

**Comment by thiagobardini** [comment]
@JulianaDonovan, can you also create the mobile version, please?

**Comment by JulianaDonovan** [comment]
Also created the mobile version. Let me know if you need anything else.
