### ISSUE TITLE
Surveyor View: display correct data on map view page

### ISSUE THREAD

**Issue by Rando-cal** [codeforboston/urban-league-heat-pump-accelerator#298]
Whenever a surveyor selects homes on the dashboard and then clicks Generate Map, the selected homes are added to `surveyor.selectedHome` in the redux store. On the subsequent page `/surveyor/map` the homes are not displayed properly (everything's `undefined`). 

In general we should probably make this workflow a bit smoother but that's out of the scope of this issue, see #335

**Comment by LWest001** [comment]
This is as opposed to being hooked up to the jsonserver? It is currently pulling from jsonserver using the apiSlice hooks, so I think just changing the `baseUrl` in apiSlice to the url of the actual API would take care of this.

**Comment by mattdelsordo** [comment]
Merging #318 should resolve the URL situation! If this is already hooked up to RTK query then this is done, but we should confirm.

**Comment by mattdelsordo** [comment]
Okay I dug into this a bit - I think what we need to "hook up" here is the `/surveyor/map` page where it shows the list of homes you've selected on the actual surveyor dashboard page. Right now it's actually putting the selected homes in redux, so there's no actual API involved here! I'll update the issue name + description.

**Comment by mattdelsordo** [comment]
Actually my bad, I got this confused with #295 so I don't think anything else needs to be done here. Closing.
