### ISSUE TITLE
Fix dropdown hover issue on navbar in public view

### ISSUE THREAD

**Issue by thiagobardini** [codeforboston/urban-league-heat-pump-accelerator#315]
**Issue:** 
Dropdown menu in the navbar redirects to incorrect page when hovering after clicking links in the footer.

**Description:** 
When hovering over the dropdown menu in the navbar after clicking links in the footer, the dropdown redirects to a page without any click interaction. This behavior is not intended and needs to be fixed.

Please refer to the attached video for a demonstration of the issue with the dropdown menu's hover behavior.

For any code-related concerns, please contact @thiagobardini.

![boston-heat-pump-acc_2023-4-12](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/25167383/a6d98258-14c1-4d81-b297-b3fd980e0095)

**Comment by johndowd** [comment]
@thiagobardini are you still having this issue on main? I'm not having the same issue on my machine
