### ISSUE TITLE
Make surveyor data available from user data

### ISSUE THREAD

**Issue by aTegart** [codeforboston/urban-league-heat-pump-accelerator#322]
Needed so that on first login, the user id from devise/user table can be used to look up the related surveyor info

OR

Update user serializer to include surveyor info

**Comment by mzagaja** [comment]
We decided to "Update user serializer to include surveyor info"

**Comment by mattdelsordo** [comment]
Wait so is this done?

**Comment by aTegart** [comment]
This is done in the sense that we decided what to do. There is a separate issue for actually doing it.
________________________________
