### ISSUE TITLE
Verify Google Maps page works properly

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#333]
I'm pretty sure this guy is good to go, but we should verify that it integrates well with the rest of the page once the rest of the surveyor lifecycle is hooked up. The transition back and forth from this should be as seamless as we can make it.

Ref: https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/76

**Comment by Rando-cal** [comment]
A static file **was** imported directly and going into Google Maps. Now the data is coming from RTK Query, so will it be pulled in and goto Google Maps and 'map' out properly?

**Comment by mattdelsordo** [comment]
Yeah it used to look like:

```
data.json --> page.js
```

now it looks like

```
rails backend \
                    OR > rtk query --> page.js
json-server    /                      
```             
Just check that the data is still displaying properly without issues, it _should_ be all hooked up.

**Comment by thiagobardini** [comment]
Following discussions with Matt, I have concluded that MapLink.js, responsible for generating home address routes in Google Maps, is functioning correctly. We just need to ensure how we will pass this data there.

However, we need improvements in the backend logic for data manipulation to reduce frontend complexity.

My proposal is to optimize the "survey_response" file for generating home address routes. By consolidating data and adding key-value pairs like "complete," "geolocation," and "homes," we can simplify request handling and ensure that all necessary information is available. These improvements will streamline data fetching and reduce frontend complexity.

We can discuss this further in our meeting.

**Comment by thiagobardini** [comment]
Here is the heat pump API written by DAT: https://lucid.app/lucidchart/204792e0-f39d-4844-b0e6-f2564340a3cf/edit?page=0_0&invitationId=inv_7da7c0c6-e588-4a10-8a09-2682e074f36e#

**Comment by mattdelsordo** [comment]
Closing this for the time being, will create a new issue if/when we integrate with the maps API
