### ISSUE TITLE
Surveyor: improve navigation between pages when filling out surveys

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#335]
Some feedback we got from Chris is that we should minimize the amount of pages a surveyor needs to access while taking surveys. So we need to make the transitions between the house list -> the map -> the survey (etc) as seamless as possible. This is kind of subjective and needs better specs but, for example, once a survey is complete is shouldn't redirect the entire way back to the surveyor dashboard.

**Comment by Rando-cal** [comment]
Get input during Beta testing.
