### ISSUE TITLE
Public user: connect to home creation API before moving to survey

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#336]
Depends on ~#190~ #341

**Comment by LWest001** [comment]
@mattdelsordo This might be done? When I run the public survey, I get the page to create a home first, then I get the survey.

**Comment by mattdelsordo** [comment]
Last I checked the home creation page just does a PUT to the database, what we need is #341 so that the data is validated.

**Comment by LWest001** [comment]
Currently `/public/survey` shows an `AddressValidatorComponent` which sends a POST to `/homes`, then displays the actual survey.

**Comment by mattdelsordo** [comment]
After #341 it looks like we can just keep using the /home POST endpoint. Need to figure out if that will error-out on us if the address is invalid, for error handling purposes.
