### ISSUE TITLE
Surveyor: survey pre-screening page

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#337]
Depends on #226

The back end team wants to filter out instances where a survey was not actually given. In this case a `survey_visit` entity will be created on their end, but not `survey_answers`. We need a screen before the surveyor survey page to support this.

**Comment by mcarre20** [comment]
@mattdelsordo 
is this still needed?

**Comment by mattdelsordo** [comment]
@mcarre20  See #226. We don't need to implement anything if there's no corresponding back end part. If back end is skipping that then we can skip this.

**Comment by mzagaja** [comment]
We do not need this!
