### ISSUE TITLE
Resolve CORS issue between frontend and backend servers

### ISSUE THREAD

**Issue by thiagobardini** [codeforboston/urban-league-heat-pump-accelerator#350]
We are encountering a CORS issue when making requests from 'http://localhost:3001/' to 'http://localhost:3000/'. The 'Access-Control-Allow-Origin' header on the backend server needs to include 'http://localhost:3001/' to resolve this issue.

Based on the suggestion from Matthew Zagaja, we can resolve this issue by utilizing the [rack-cors gem](https://github.com/cyu/rack-cors), which is expected to provide a straightforward fix.

Thank you.

**Comment by mzagaja** [comment]
Resolved in 457de18f10ece787bcbd0f19b283caa56467c608
