### ISSUE TITLE
Create Dockerfile to build/host static website files

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#354]
We can do the build + host with a multi-stage Dockerfile. End result can just be static files served by nginx

Maybe useful: https://docs.docker.com/build/building/multi-stage/

**Comment by Rando-cal** [comment]
2 images: Production (more important) and a Dev.

**Comment by Rando-cal** [comment]
Check Fly.io or render.com

**Comment by Rando-cal** [comment]
Its up but not serving anything when its hit..... hmmmm.....


Dockerfile:


FROM node:18.16-alpine3.17


ENV YARN_VERSION 1.22

WORKDIR /front

COPY package.json ./front

RUN yarn policies set-version $YARN_VERSION
RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "start"]

**Comment by Rando-cal** [comment]
Next attempt is to use a Ubuntu base image and build the environment up from scratch.

**Comment by Rando-cal** [comment]
Once completed we can check if its efficient enough on production. If not, then we can add 'lazy loading'

**Comment by mikelynch** [comment]
Is there a PR for this somewhere?

**Comment by Rando-cal** [comment]
I got a basic one working see the README in /frontend/front/ and follow the directions.  I need to add more complex security and copy over the container itself (~ 400mb).

**Comment by Rando-cal** [comment]
PR is out for this
