### ISSUE TITLE
Surveyor View:  On survey page, survey questions with an "other" option give user 2 inputs to specify "other"

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#367]
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/64639764-87b6-44fe-bdd0-659f9a89971e)

![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/17c54ce9-8c1f-4c62-a988-1fb669c03a49)

**Comment by mikelynch** [comment]
Not sure if this is based on the dummy survey we looked at or whether this is something from the UI component. At present, we have explicit separate “if other, please specify” questions. Originally, the idea was that we had questions like: 
What type of heating system? (Forced hot air/Radiators/Other), then a separate question with “if other, what”?

If the UI is smart enough to handle showing a separate text box for other, I think we'd be fine to remove the separate question – ultimately in the database, we store `survey_answers` with a text `answer` field – so if the recipient picks “forced hot air”, we'll store that, and if they select “Other” and then write another response, we could store that instead.

**Comment by LWest001** [comment]
> Not sure if this is based on the dummy survey we looked at or whether this is something from the UI component. At present, we have explicit separate “if other, please specify” questions. Originally, the idea was that we had questions like: What type of heating system? (Forced hot air/Radiators/Other), then a separate question with “if other, what”?
> 
> If the UI is smart enough to handle showing a separate text box for other, I think we'd be fine to remove the separate question – ultimately in the database, we store `survey_answers` with a text `answer` field – so if the recipient picks “forced hot air”, we'll store that, and if they select “Other” and then write another response, we could store that instead.

@mikelynch I like that idea. In that case, is this an issue that can be handled on the backend and we can leave the UI the same?

**Comment by LWest001** [comment]
@mikelynch Yes it does.

**Comment by LWest001** [comment]
@mikelynch can I assign this issue to you?

**Comment by mikelynch** [comment]
I didn't think this required anything on the backend, no? Happy to clean up the dummy questions to remove the “if other, please specify”, but I think the rest is frontend logic.

**Comment by LWest001** [comment]
Right now the UI pulls up an "other" field when an "other" option is selected (as intended), so I think we just need to remove the "if other, please specify" from the survey questions. I may have misunderstood your previous comment!

**Comment by mikelynch** [comment]
As far as I know, we don't have the “real“ (i.e. final) survey questions – I just put together some dummy ones. Happy to remove those extra questions but we probably need to update them all anyway.

**Comment by LWest001** [comment]
> As far as I know, we don't have the “real“ (i.e. final) survey questions – I just put together some dummy ones. Happy to remove those extra questions but we probably need to update them all anyway.

Gotcha. I think we can just close the issue for now and keep it in mind when we put the final surveys together!
