### ISSUE TITLE
Admin view: Search bar in <Home/> component should filter visible homes

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#373]

**Comment by Rando-cal** [comment]
I believe we should use Material UI : Quickfilter as its supported by the free version.

**Comment by Rando-cal** [comment]
PR is out for this

**Comment by Rando-cal** [comment]
Fix for PR Randy searches #425, should be fixed. Review PR

**Comment by mzagaja** [comment]
@Rando-cal What did you mean by [this is moot](https://github.com/codeforboston/urban-league-heat-pump-accelerator/pull/425#issuecomment-1767427614)? Are we ok to close this issue now?

**Comment by Rando-cal** [comment]
This is fixed from another PR. All set.  Closing
