### ISSUE TITLE
Admin view: remove selection menu

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#374]
This currently exists in the Admin view but no the Surveyor view.

**Comment by LWest001** [comment]
@mattdelsordo given #355, should this issue be closed? Or, changed to remove 'Selection Menu' from the admin view?

**Comment by mattdelsordo** [comment]
I think the latter is a better option. If you want to do surveyor stuff I think you should have to log in with a surveyor account

**Comment by Rando-cal** [comment]
Deleted code
