### ISSUE TITLE
Surveyor view: Assignment homes list - clicking dialog menu should show [something] instead of 'undefined undefined'

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#375]
What data is meant to be displayed here?

![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/20c5806a-1548-415a-bb71-ed2d2ec01123)

**Comment by Rando-cal** [comment]
fixed undefined.
