### ISSUE TITLE
Surveyor view: Feed valid data to Map page when clicking Generate Maps

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#377]
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/d7241123-1902-46ec-9a34-1e16c1078a76)

**Comment by mattdelsordo** [comment]
Potential duplicate of #295

**Comment by Rando-cal** [comment]
Looks good on latest Main
