### ISSUE TITLE
Import Actual Data with Clusters

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#384]
Write a rake task/update the seed to import the actual clusters that are to be surveyed. Likely from the file at https://raw.githubusercontent.com/codeforboston/urban-league-heat-pump-accelerator/main/data-analysis/clustered_ordered_parcels.csv.

**Comment by aTegart** [comment]
Using the column names from the data team's dataset ([here](https://raw.githubusercontent.com/codeforboston/urban-league-heat-pump-accelerator/main/data-analysis/clustered_ordered_parcels.csv)) and the original property assessments table structure from schema.rb ([here](https://github.com/codeforboston/urban-league-heat-pump-accelerator/blob/a303956d41b4965944bff7cdddffb0ddf7f219e9/backend/db/schema.rb)), we cleaned up and sorted the column names so we could compare them in a text diff tool to see what the difference was. The full cleaned lists of column names are below (copy into a tool like [this](https://text-compare.com/) to see the diff)

### Data team
```
ac_type
ac_type_score
bed_rms
bedroom_score
bldg_type
city
cluster
ext_cond
ext_finished
fire_place
floor_score
geocoded
geometry
gis_id
gross_area
heat_fuel
heat_type
heat_type_score
int_cond
int_wall
land_sf
latitude
living_area
living_space_frag_score
living_space_fragmentation
longitude
lu
lu_desc
mail_address
mail_city
mail_zipcode
map_par_id
order
own_occ
owner
pid
res_floor
space_between_houses
st_name
st_num
structure_class
total_score_x
tt_rms
unit_num
yr_built
yr_built_category
yr_built_score
yr_remodel
zipcode
```

### PROP ASSESSMENTS
```
ac_type
bdrm_cond
bed_rms
bldg_seq
bldg_type
bldg_value
bthrm_style1
bthrm_style2
bthrm_style3
cd_floor
city
cm_id
com_units
corner_unit
created_at
ext_cond
ext_finished
fire_place
full_bth
gis_id
gross_area
gross_tax
heat_fuel
heat_type
hlf_bth
int_cond
int_wall
kitchen
kitchen_style1
kitchen_style2
kitchen_style3
kitchen_type
land_sf
land_value
living_area
lu
lu_desc
luc
mail_address
mail_addressee
mail_city
mail_state
mail_zipcode
num_bldgs
num_parking
orientation
overall_cond
own_occ
owner
pid
prop_view
rc_units
res_floor
res_units
roof_cover
roof_structure
st_name
st_num
structure_class
total_value
tt_rms
unit_num
updated_at
yr_built
yr_remodel
zipcode
```

**Comment by mikelynch** [comment]
Resolved by 439.
