### ISSUE TITLE
Admin: edit users

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#404]

**Comment by Rando-cal** [comment]
@mattdelsordo  Was this the Devise code holding this up?

**Comment by mattdelsordo** [comment]
This depends on #422

**Comment by mcarre20** [comment]
@mattdelsordo 
Are we still waiting on password reset/change functionality?

**Comment by mattdelsordo** [comment]
Yeah, see #422, it's the back end side of this.

**Comment by mzagaja** [comment]
Is the purpose of this ticket to let an admin change details about users? Or is it for the user themselves to update their own profile? It's unclear to me how this is dependent upon password reset.

**Comment by mattdelsordo** [comment]
I think there might be some mixed messages in this thread, this was for allowing admins to edit user info but it seems to me that SHOULDN'T include passwords. Password editing was blocking the user-side account editing.
