### ISSUE TITLE
Admin: fixes for home profile page

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#413]
- Add unit number to the page
- Remove everything below building type
- Hook up to react hook forms to allow edit/save
- treat zip code as a string instead of as a number
- Add a component to link to the survey visits associated with this home

**Comment by mattdelsordo** [comment]
This should probably hook into the back end's Pelias situation (#341) but that isn't ready yet

**Comment by mcarre20** [comment]
[PR#448](https://github.com/codeforboston/urban-league-heat-pump-accelerator/pull/448)
