### ISSUE TITLE
Add Language Support to Backend

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#414]
* Double check that survey questions/answers support unicode and not just ASCII (for supporting accented Spanish characters)
* Add language to the SurveyResponse
* Add a new text column and response_options column per language to SurveyQuestion

**Comment by mikelynch** [comment]
@mzagaja It sounded like this was on hold based on concerns about recording the language of the survey response. Should this be closed as won't fix?

**Comment by mzagaja** [comment]
Let's circle back with Christopher on this. I don't recall the final decision on this.
