### ISSUE TITLE
Implement Devise password change/recovery lifecycle

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#422]
It looks like Devise has a whole lifecycle to reset passwords involving sending an email to the user that we need some back end support on. Not 100% on how this works but it involves the `:recoverable` module: https://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Recoverable

Also see here: https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-edit-their-password but it might be different in devise-jwt land.

It seems like the lifecycle is something like:
- user hits password reset endpoint
- backend then sends an email with a special link
- that special link has a token in it so if the user clicks it the front end can send it to the back end when changing the password to make sure the password change request is legit

https://stackoverflow.com/questions/56170014/devise-with-jwt-recoverable-reset-password-by-token

We'll then have to hook this up on the front end and create the UI for password resets.

**Comment by mzagaja** [comment]
This makes sense. We have a SendGrid free account we can setup with an API key for this.

**Comment by mzagaja** [comment]
Fixed in 3ac512a4a8b235cfa8d0cc40edd7636fcc7aefb4

**Comment by mzagaja** [comment]
Closed because this should be ready for front-end. If we have to re-open we will responsibly do so with more notes about what specifically the backend needs to do.

**Comment by Rando-cal** [comment]
March 12 - Matt Z. everything should be in place, but we need to find the routes for it. Maybe a PUT or POST.

**Comment by mzagaja** [comment]
@Rando-cal See https://paw.pt/iJjUbPQc for how to send a password reset
