### ISSUE TITLE
Make sure map opens in phone app instead of browser tab

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#429]
* might need a long-press on the phone side (at least on iOS)
* might need a special URI format
* might need to be a real <a> link instead of a button calling `window.open`

**Comment by LWest001** [comment]
@mattdelsordo, do you mind explaining your trick for running the backend when using mobile?

**Comment by mattdelsordo** [comment]
Step 1: figure out what your local IP is (`192.168.x.x`, not `localhost`)
Step 2: run the dev server with `REACT_APP_API_URL={your IP}` (or just manually change the baseUrl in apiSlice.js)
Step 3: navigate to `{your IP}: 3001` on your phone when connected to the same wifi network as the computer running the dev server

**Comment by mattdelsordo** [comment]
I've confirmed that this works at least in Android + Chrome. It does NOT work in Android + Firefox.

**Comment by mattdelsordo** [comment]
@LWest001 "de"-confirmed that this does NOT work on iOS, so there's work to be done there.

**Comment by mattdelsordo** [comment]
- We're using window.open rather than a proper link, which may be a part of the problem. 
- Specify to use a specific recommended browser for best experience
- In general: we should be using react-router Links instead of <a>s/etc.

**Comment by mattdelsordo** [comment]
Potentially helpful link: https://developers.google.com/maps/documentation/urls/ios-urlscheme
At minimum, I think we want to have this working in iOS+Safari+Apple Maps and Android+Chrome+Google Maps (already working)

**Comment by LWest001** [comment]
### Helpful links
[Detecting user's browser/OS with browser APIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent)
[Google Maps URL Scheme for iOS](https://developers.google.com/maps/documentation/urls/ios-urlscheme)
