### ISSUE TITLE
Allow admins to create new survey structures

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#431]
An admin should be able to click on a survey in the survey table and edit/save the data. The new survey button should take an admin to the same page with blank fields for creating a new survey.

**Comment by mcarre20** [comment]
@mattdelsordo 
do we still need this?

**Comment by mattdelsordo** [comment]
@mcarre20 is the functionality missing or do they explicitly not want people creating/updating surveys through the API? If it's the latter then yeah we can skip this.

**Comment by mattdelsordo** [comment]
We talked through this and decided that letting users create + edit survey structures dynamically would leave to a bunch of problems based on how survey structure data is stored. For example this would break matching questions to answers based on question number, and editing question text might lead to responses that no longer make sense. We should deprioritize this feature.

If we do this, we should let Admins upload entire CSVs that create a whole new survey with a new ID. See `seed_importer.rb` in the back end code for the current logic for this.

**Comment by Rando-cal** [comment]
This is not needed during this version.
