### ISSUE TITLE
Fix Surveyor hamburger menu

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#434]
Problems with surveyor hamburger menu when in mobile aspect ratio:
1. icons are all mail icons, they should match the role of the option
2. "House Profile" needs to be removed
3. Log out doesn't log out properly
4. Dashboard and Account options DO work, no changes needed here

**Comment by LOGESH-B** [comment]
Hii @mattdelsordo 
Are you expecting this
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/86541143/fad8cfba-22eb-4032-87f5-5fc02695cb48)

How can I login to Surveyor and admin panel?

**Comment by mattdelsordo** [comment]
How are you accessing the site? If you boot it up locally it should default to the view selection screen. On vercel, the login button is at the bottom of the public view footer, but it probably doesn't work to log in.

**Comment by LOGESH-B** [comment]
Hii @mattdelsordo 
I am running the website on local machine ...yes it first renders the view sellection page ......I only have access to Public view ...both admin and surveyor view page asks for login.

**How can I login to Surveyor and admin panel?** I am asking this question to view and do the changes in those pages aswell

So, I worked on the navbar to Provide the icon on the public view page.

![](https://user-images.githubusercontent.com/86541143/254745428-fad8cfba-22eb-4032-87f5-5fc02695cb48.png)


[Make sure navbars turn into hamburger menus in mobile mode
Make sure navbars and hamburgers have the same options] I think this two things are already fixed..navbar is responsive and the options are also looks similar

**Tell me is there any changes  **←****

**Comment by mattdelsordo** [comment]
Ah, so if you want login to work, you'll have to be running the back-end as well. You can find test-logins in `backend/lib/seeds/test_users.csv`.

That said, this issue was not meant to be related to the public view at all, this is pertaining to the nav bars for the admin and surveyor views which have some discrepancies in what options they display. This issue probably needs to be fleshed out a bit more.

**Comment by LOGESH-B** [comment]
Hii @mattdelsordo 
While running backend it shows error

$ bundle exec rails db:prepare
rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied


Caused by:
PG::ConnectionBad: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

Tasks: TOP => db:prepare
(See full trace by running task with --trace)

**Comment by mattdelsordo** [comment]
@LOGESH-B I'm not sure this is the appropriate place to troubleshoot running the app, you might have better luck in the Code for Boston slack

**Comment by LWest001** [comment]
Something I noticed today: The links in the hamburger menu from surveyor view don't actually work.
