### ISSUE TITLE
Migrate Columns from Strings to Booleans

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#45]
In the data schema `:own_occ` and `:corner_unit` need to have migrations written to convert them from String types to Booleans or we need to figure out whether we shoudl use enum or keep them String types depending on the data we want to preserve. Needs further investigation as to what values are in the field, get some examples of the outliers and the we can ask Christopher Scranton.

**Comment by lhuhmann** [comment]
The data descriptions (at https://data.boston.gov/dataset/property-assessment/resource/db9d1e04-080b-4477-96e0-c440f3ff29f1) seem to describe these as yes/no.

* `:own_occ`
  * The description reads: "Residential Exemption: “Y” character code indicating if owner receives residential
exemption as an owner-occupied property"

* `:corner_unit`
  * The description reads: "Indicates if the unit is locating in the corner of the building (Y/N)"
 

I also confirmed that the 2022 data (from https://data.boston.gov/dataset/property-assessment/resource/4b99718b-d064-471b-9b24-517ae5effecc) in these columns take values that can be straightforwardly translated into Boolean values:

![image](https://user-images.githubusercontent.com/6555306/213308459-68844da7-adf6-44ff-8024-b234f8e98381.png)

If we only need to accommodate the 2022 data (I didn't check older data sets), and if there will be an opportunity for the data to be transformed to Boolean as part of the data pipeline, then I think using Boolean in the database makes sense, and it does not appear that this would result in information loss.
