### ISSUE TITLE
Back-end pagination for tables

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#451]
Since there's 1000s of Homes/etc. we should use back end pagingation to load N homes/etc at a time instead of getting all of them at once

**Comment by LWest001** [comment]
Would paginating by loading N homes at a time break the sort/filter function? Like, it would just sort/filter the batch of homes currently visible?

If it does, the solution might be to query homes immediately on login in the background then pass it down as a prop or with the context api.

**Comment by LWest001** [comment]
Just thinking out loud here: maybe there is a way to break out of the MUI DataGrid filter/sort system to instead use REST API filtering and sorting combined with pagination.

**Comment by mattdelsordo** [comment]
That's a good point, and I think you're right, if we use server-side pagination then we'll probably have to use server-side sorting as well.

**Comment by LWest001** [comment]
@mattdelsordo I'm thinking about closing this as not planned - thoughts?

**Comment by mattdelsordo** [comment]
@LWest001 go for it

**Comment by LWest001** [comment]
No longer part of plan
