### ISSUE TITLE
Launch Issue List

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#461]
- [x] Routes other than the `/` root route do not work. Can only navigate by clicking links from www.bostonhpa.org
- [x] Backend not currently loading in Mass Open Cloud deployment
- [x] Add SSL to frontend and backend
- [x] Need to enumerate public route for backend api.
- [x] Make sure ENV vars are set correctly when being built.

**Comment by mattdelsordo** [comment]
The routing issue is probably a nginx configuration thing: https://gkedge.gitbooks.io/react-router-in-the-real/content/nginx.html
