### ISSUE TITLE
Make sure redux + react development plugins aren't available in production

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#473]
Redux lets you inspect the page's store with a browser plugin (Redux DevTools), but we don't want this to be enabled in production (at time of writing, it is). I think we should be able to set the environment variable `NODE_ENV=PRODUCTION` or something like that, but CRA should be doing that automatically, so I'm not sure what's up.

We also want to disable React Developer Tools (the React extension) in production.

**Comment by mcarre20** [comment]
@mattdelsordo 
do we have a list of the plugins that need to be removed?

**Comment by mattdelsordo** [comment]
@mcarre20 updated the description, whoops
