### ISSUE TITLE
Add back survey_visit_ids to homes endpoint

### ISSUE THREAD

**Issue by mikelynch** [codeforboston/urban-league-heat-pump-accelerator#487]
Ensure that homes endpoint returns a list of survey_visit_ids for that home. Also should return this when nested within list of assignments.

**Comment by EfrainAD** [comment]
http://localhost:3000/homes return an array of 
```
{
        “id”: 2312,
        “street_number”: “73”,
        “street_name”: “BURT ST”,
        “unit_number”: null,
        “city”: “DORCHESTER”,
        “state”: “MA”,
        “zip_code”: “02124",
        “building_type”: “SINGLE FAM DWELLING”,
        “status”: “uncanonicalized”,
        “user_added”: false,
        “assignment_id”: 68,
        “visit_order”: 42,
        “latitude”: “42.28408477”,
        “longitude”: “-71.07040778”,
        “visited”: false,
        “completed”: false,
        “url”: “http://localhost:3000/homes/2312.json”
}, 
```
this is missing survey_visit_ids: [……] that used to be there. 

Also http://localhost:3000/assignments returns an array of homes inside it. This should also have that survey_visit_ids field in it. (The old build (docker) had it missing, so I made sure to mention it here.)

(Was ask in slack to 'whip that up', as for the comment. Probably a bit too detailed.)

**Comment by mikelynch** [comment]
@EfrainAD , does this look okay now?
