### ISSUE TITLE
Integrate language selection with public survey page

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#492]
- Chosen language from drop-down should dictate which language is requested from API
- If English or Spanish is selected, request English or Spanish survey
- If any other language is selected, notify user that the survey is not yet available in their language and request English survey
- Error handling in case a request is sent to the backend for survey in a language that does not exist

**Comment by mzagaja** [comment]
Resolved by https://github.com/codeforboston/urban-league-heat-pump-accelerator/pull/618
