### ISSUE TITLE
Fix Broken Link

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#520]
The link under testimonials to https://goclean.masscec.com/customer-story/peter-installs-an-air-source-heat-pump-system/?utm_medium=cpc&utm_source=google&utm_campaign=brand is busted. We need a new destination for this. It is linked from the "Read More" button here:
<img width="1266" alt="image" src="https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/565647/6098adfa-e63d-4832-a1f8-cad9841ae8d2">

**Comment by mcarre20** [comment]
we'll have check with Christopher if this link is a good replacement:
https://goclean.masscec.com/customer-stories-2/?tx_clean_energy_solutions=air-source-heat-pumps

**Comment by Rando-cal** [comment]
Posed the question to Christopher on Slack.

**Comment by Rando-cal** [comment]
Chris's new link : https://goclean.masscec.com/customer-story/ashp-nias-new-floor-mounted-air-source-heat-pump/

**Comment by Rando-cal** [comment]
Merged to main
