### ISSUE TITLE
Password reset - override devise passwords controller to verify reset token

### ISSUE THREAD

**Issue by aTegart** [codeforboston/urban-league-heat-pump-accelerator#546]
We want to show an error if the password reset token is invalid before allowing user to see the password reset form (instead of waiting for them to submit)

Update this in the devise passwords_controller to support json payload for verifying password reset token (error about no template for html blocking frontend)

![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/27782045/2d85a647-a713-43fa-9aea-ba183a7a07b5)

**Comment by mzagaja** [comment]
See https://github.com/heartcombo/devise/blob/a259ff3c28912a27329727f4a3c2623d3f5cb6f2/lib/devise/models/recoverable.rb#L129-L156 for the method devise uses for this.
