### ISSUE TITLE
Provide Assignment Status

### ISSUE THREAD

**Issue by mcarre20** [codeforboston/urban-league-heat-pump-accelerator#567]
If all survey are complete make show assignment as completed otherwise show assignment as incomplete

**Comment by mikelynch** [comment]
How do we decide if a survey is completed? Is it if there exists at least one survey visit for that home?

**Comment by mcarre20** [comment]
That is correct, once a survey is submitted, we mark the home as completed.

**Comment by mcarre20** [comment]
not needed
