### ISSUE TITLE
add password

### ISSUE THREAD

**Issue by runkelcorey** [codeforboston/urban-league-heat-pump-accelerator#59]
### Overview
Don't want to share half-baked analyses with the world. Add a password that needs to be entered correctly before app displays information.

### Action Items
- [ ] research possible ways to add password and not have anything shown until password is entered correctly

### Resources/Instructions
* would Google how others have done this, may need to translate to Python

**Comment by dwreeves** [comment]
I suppose you are talking about the Shiny app (that you want to translate into Python)?

In principle, this is not hard, but how you do this is entirely dependent on how you are implementing said application, and what framework you are using. So you need to figure that part out first before you can add a password.

That said, I also think adding a password may not be super necessary at this stage, either, unless you anticipate that the team will soon be working with confidential data. It's unlikely there is anyone who is both interested in this project's work, but not already accessing the work via the Slack or meetings. And the adverse impact of such a person looking at what is going on would be very minimal so long as we are only using publicly available data.
