### ISSUE TITLE
Migrate zip code columns to 5 digit numbers

### ISSUE THREAD

**Issue by jonnycodesalot** [codeforboston/urban-league-heat-pump-accelerator#67]
Current seed implementation pulls the `zipcode `and `mail_zipcode `fields in as strings.  Need to have these as numbers

**Comment by jonnycodesalot** [comment]
Hmmmm, @mzagaja so do we want numbers, where we can't force leading 0's, or strings, where we can?

**Comment by mzagaja** [comment]
I would say `String` is the right type for a ZIP code. A ZIP Code denotes a route for a mail carrier. You can easily replace the numbers with letters or emoji and it could still serve the same function. Other than the fact that ZIP codes near each other tend to start with similar digits, there isn't much value to treating them as numbers.
