### ISSUE TITLE
Create Admin > House page

### ISSUE THREAD

**Issue by Zevez7** [codeforboston/urban-league-heat-pump-accelerator#83]
### Overview
Create the admin view of the house page. No mobile view. Tablet view and larger. This house page will display information on the house that is being viewed by the admin to look at the surveyor questions and answers. 

### Action Items
Display these data
- Address
- Other home owner data
- Surveyor name that assessed the 
- Date of survey 
- Display Questions as expanded table use (material ui accordion)
- Display Assessment as expanded table (material ui accordion)
- Delete button
- Edit button

**Comment by smsada** [comment]
Here is a mock-up of the page

![Image](https://user-images.githubusercontent.com/38507899/197893788-1394ef33-7bdb-4bb4-bade-44fdb0ddfcce.png)

[Figma Source](https://www.figma.com/file/nshcpSmmOOTbkDbJWPbt9W/ULEM---Wireframe?node-id=1306%3A14000)
